version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
        - npm install
    build:
        - npm run build
        - aws s3 sync dist s3://dev-fit-s-marky --delete
