name: Cypress
on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: cypress-io/github-action@v1
        with:
          start: yarn start
          wait-on: 'http://localhost:3010'
          browser: chrome
          headless: true
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: __test__/cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: __test__/cypress/screenshots
