name: Cypress
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: cypress-io/github-action@v1
        with:
          start: yarn start
          wait-on: 'http://localhost:3010'
          command-prefix: 'percy exec -- npx'
          browser: chrome
          headless: true
